### ISSUE TITLE
Add tests to the app 

### ISSUE THREAD

**Issue by faiqali1** [faiqali1/File-Organiser#3]
How do you add tests to such an app?

I am planning to use pytest, but not quite sure how to test such an app?

**Comment by rafidini** [comment]
Hi @faiqali1,

If you want to test your app, you should consider separating your main script and the different utility functions that you will call inside your main script.

Like this : 
```
pyproject.toml
src/
    mypkg/
        __init__.py
        app.py
        view.py
tests/
    test_app.py
    test_view.py
    ...
```
> **source**: https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html

Afterward you can automatically run tests on GitHub with Actions. I can help you with that if needed!

Good luck

**Comment by faiqali1** [comment]
Hi @rafidini 

Thanks for the comments, I'll structure my app as such and help would be very much appreciated. I'm more confused on the fact that since the app moves files into folder. How am I gonna test that? 
I could make a folder every time but I don't reckon that's the best approach. 

Many thanks,
